"""Database backend adapter — SQLite (default) or Postgres/Supabase.

`Store` (cadio/store.py) is written against SQLite's DB-API with `?` placeholders.
This module lets the exact same query code run on Postgres when `DATABASE_URL` is
set, so the port is a config change, not a rewrite:

- `connect()` returns a per-thread connection. For SQLite it's a real
  `sqlite3.Connection` (WAL). For Postgres it's a thin wrapper that translates
  `?`→`%s`, yields dict rows (so `row["col"]` and `dict(row)` keep working), and
  reconnects once if Supabase dropped an idle connection.
- `schema_sql()` returns the dialect-appropriate DDL statements.
- `upsert_sql()` builds the right "insert-or-replace" for each dialect.

The Store keeps its process-wide write lock on both backends (correctness first);
reads use the per-thread connection with no lock. Postgres runs in autocommit so
we never leave an idle-in-transaction connection open on the Supabase pooler.
"""

from __future__ import annotations

import sqlite3
from typing import Any

from . import config

is_postgres = config.is_postgres


# ---- schema (dialect-specific only where it must be) ------------------------

# messages.id is the one column that differs: SQLite autoincrement vs Postgres
# identity. Everything else (TEXT/INTEGER/REFERENCES/INDEX, IF NOT EXISTS) is
# common SQL. {ID} is filled per dialect.
_SCHEMA_TMPL = """
CREATE TABLE IF NOT EXISTS users (
    id          TEXT PRIMARY KEY,
    google_sub  TEXT UNIQUE,
    email       TEXT UNIQUE NOT NULL,
    name        TEXT,
    picture     TEXT,
    created_at  TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS projects (
    id          TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    archived_at TEXT,
    thumb_run   TEXT,
    user_id     TEXT
);
CREATE TABLE IF NOT EXISTS messages (
    id         {ID},
    project_id TEXT NOT NULL REFERENCES projects(id),
    role       TEXT NOT NULL,
    content    TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_project ON messages(project_id, id);
CREATE TABLE IF NOT EXISTS runs (
    id            TEXT NOT NULL,
    project_id    TEXT NOT NULL REFERENCES projects(id),
    parent_run_id TEXT,
    label         TEXT,
    ok            INTEGER NOT NULL,
    meta          TEXT NOT NULL,
    created_at    TEXT NOT NULL,
    PRIMARY KEY (project_id, id)
);
CREATE TABLE IF NOT EXISTS assets (
    id         TEXT NOT NULL,
    project_id TEXT NOT NULL REFERENCES projects(id),
    file       TEXT NOT NULL,
    name       TEXT NOT NULL,
    mime       TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (project_id, id)
);
-- R2 free-tier accounting (used only when object storage is enabled).
CREATE TABLE IF NOT EXISTS r2_usage (
    period   TEXT PRIMARY KEY,   -- 'YYYY-MM' (UTC)
    class_a  INTEGER NOT NULL DEFAULT 0,
    class_b  INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS r2_objects (
    key            TEXT PRIMARY KEY,
    size_bytes     INTEGER NOT NULL,
    last_access_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_r2_objects_lru ON r2_objects(last_access_at);
"""


def schema_statements() -> list[str]:
    id_col = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if is_postgres()
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    sql = _SCHEMA_TMPL.format(ID=id_col)
    # split into individual statements (psycopg executes one at a time; sqlite is
    # fine either way). Comment lines are stripped so they don't swallow a stmt.
    out: list[str] = []
    for chunk in sql.split(";"):
        lines = [ln for ln in chunk.splitlines() if not ln.strip().startswith("--")]
        stmt = "\n".join(lines).strip()
        if stmt:
            out.append(stmt)
    return out


def upsert_sql(table: str, columns: list[str], conflict: list[str]) -> str:
    """Dialect-correct INSERT-or-replace for a whole row.

    SQLite: INSERT OR REPLACE. Postgres: INSERT … ON CONFLICT (keys) DO UPDATE.
    Uses `?` placeholders (translated for pg by the connection wrapper).
    """
    cols = ", ".join(columns)
    marks = ", ".join("?" for _ in columns)
    if not is_postgres():
        return f"INSERT OR REPLACE INTO {table}({cols}) VALUES ({marks})"
    updates = ", ".join(f"{c}=EXCLUDED.{c}" for c in columns if c not in conflict)
    keys = ", ".join(conflict)
    return (
        f"INSERT INTO {table}({cols}) VALUES ({marks}) "
        f"ON CONFLICT ({keys}) DO UPDATE SET {updates}"
    )


# atomic "increment a monthly counter only if under cap" — returns a row when it
# incremented, nothing when the cap is already reached. Same shape both dialects.
def bump_counter_sql(column: str) -> str:
    return (
        f"UPDATE r2_usage SET {column} = {column} + ? "
        f"WHERE period = ? AND {column} < ? RETURNING {column}"
    )


# ---- Postgres connection wrapper -------------------------------------------

def _translate(sql: str) -> str:
    # our SQL never uses a literal % (no LIKE), so escaping then swapping is safe.
    return sql.replace("%", "%%").replace("?", "%s")


class _PgCursorResult:
    """Wraps a psycopg cursor to expose just fetchone/fetchall like sqlite3."""

    def __init__(self, cur):
        self._cur = cur

    def fetchone(self):
        try:
            return self._cur.fetchone()
        except Exception:
            return None

    def fetchall(self):
        return self._cur.fetchall()


def connection_params(url: str) -> dict:
    """DATABASE_URL -> psycopg connection kwargs.

    Prefer psycopg's own URI parser (handles a properly %-encoded URL, and
    URL-decodes it into literal kwargs). If that fails — almost always because
    the password was pasted with raw special characters like '/', '@', '?' or
    ':' (common with Supabase passwords) — fall back to a tolerant manual split
    so nobody has to percent-encode the password by hand.
    """
    from psycopg.conninfo import conninfo_to_dict

    try:
        return conninfo_to_dict(url)
    except Exception:
        return _split_url_tolerant(url)


def _split_url_tolerant(url: str) -> dict:
    # scheme://user:password@host:port/dbname?k=v&... — the password may contain
    # unescaped specials, so split from the OUTSIDE in: userinfo is everything
    # before the LAST '@'; the query/path live in the host section only.
    rest = url.split("://", 1)[-1]
    userinfo, _, hostsection = rest.rpartition("@")
    user, _, password = userinfo.partition(":")   # split on FIRST ':' only
    hostport, _, pathq = hostsection.partition("/")
    path, _, query = pathq.partition("?")
    host, _, port = hostport.partition(":")
    params: dict[str, str] = {"host": host}
    if user:
        params["user"] = user
    if password:
        params["password"] = password
    if port:
        params["port"] = port
    params["dbname"] = path or "postgres"
    for kv in query.split("&"):
        if "=" in kv:
            k, v = kv.split("=", 1)
            params[k] = v
    return params


class PgConnection:
    """Minimal sqlite3.Connection-compatible facade over psycopg3.

    Exposes execute/executescript/commit — the only surface Store touches.
    Autocommit is on (no idle-in-transaction against the Supabase pooler); the
    Store's own write lock provides write atomicity. Reconnects once if the
    server dropped the connection while idle.
    """

    def __init__(self):
        self._conn = None
        self._connect()

    def _connect(self):
        import psycopg
        from psycopg.rows import dict_row

        # prepare_threshold=None: no server-side prepared statements, required for
        # Supabase's transaction-mode pooler (PgBouncer) to be safe.
        self._conn = psycopg.connect(
            autocommit=True,
            row_factory=dict_row,
            prepare_threshold=None,
            **connection_params(config.DATABASE_URL),
        )

    def execute(self, sql: str, params: tuple | list = ()):  # noqa: D401
        import psycopg

        stmt = _translate(sql)
        try:
            cur = self._conn.cursor()
            cur.execute(stmt, tuple(params))
            return _PgCursorResult(cur)
        except psycopg.OperationalError:
            # dropped idle connection — reconnect once and retry.
            self._connect()
            cur = self._conn.cursor()
            cur.execute(stmt, tuple(params))
            return _PgCursorResult(cur)

    def executescript(self, script: str) -> None:
        for stmt in script.split(";"):
            if stmt.strip():
                self.execute(stmt)

    def commit(self) -> None:
        # autocommit is on; kept so Store's `.commit()` calls are no-ops.
        pass


# ---- connection factory ----------------------------------------------------

def open_connection(db_path: Any = None):
    """Open a NEW connection. Postgres when DATABASE_URL is set, else SQLite.

    Caller owns caching (Store keeps one per thread) so multiple Store instances /
    custom test paths stay isolated.
    """
    if is_postgres():
        return PgConnection()
    conn = sqlite3.connect(str(db_path or config.DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn
